# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, max_length=1024, null=True)),
                ('slot', tagging.fields.TagField(blank=True, max_length=255)),
                ('clicks', models.PositiveIntegerField(blank=True, default=0)),
                ('views', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateBanner',
            fields=[
                ('banner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banners.Banner')),
                ('image', models.ImageField(null=True, upload_to='banners')),
                ('url', models.URLField(blank=True)),
                ('template', models.CharField(default='banner.html', max_length=70)),
            ],
            bases=('banners.banner',),
        ),
    ]
