# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=126, null=True)),
                ('description', models.TextField()),
                ('rendered', models.TextField(blank=True, editable=False, null=True)),
                ('author', models.SlugField(default='anon', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('metadata', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
